version: 1.0
provider:
  name: openfaas
  gateway: https://openfaas.do.noodles.gr
functions:
  github-bot:
    lang: golang-http
    handler: ./github-bot
    image: geoah/github-bot:latest
    build_args:
      GO111MODULE: on
